### ISSUE TITLE
Not able to install docker image for face detetction and run the speech-recognition

### ISSUE THREAD

**Issue by soumenms2015** [cltl/pepper#2]
How to install openface docker on windows 7 ?

Please also mention the detailed instruction to run this repo.

**Comment by BramKraai** [comment]
Hi,

Please refer to our [WIKI](https://github.com/cltl/pepper/wiki) for all details on how to install and run the package.

According to [this](https://docs.docker.com/docker-for-windows/install/), Docker is only available on Windows 10 64bit: Pro, Enterprise or Education, since it relies on Microsoft Hyper-V. Apparently, one can install [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/) on Windows machines that do not meet the criterion. Please keep in mind that I did not test this, but they state you can run containers, which is what you need to run OpenFace, so it should work!

Once Docker is running, information on how to install OpenFace can be found [here](https://github.com/cltl/pepper/wiki/Installation#3-openface--docker).

Detailed information on how to run the package once it is installed can be found [here](https://github.com/cltl/pepper/wiki/Installation#running)

**Comment by soumenms2015** [comment]
How can I run this repo without face detection as my current system doesn't allow to install docker? I would like to test Speech to Text.

**Comment by BramKraai** [comment]
If you go to ``pepper/test/app/verbose.py``, you can run an absolute minimal application. In the class definition, you can see that the ``VerboseApp`` inherits from multiple components. You can remove any from this list to disable that feature. Please modify it to your needs.

For more information on components, please refer to [WIKI/Components](https://github.com/cltl/pepper/wiki/How-it-works#components)

e.g. if you want only speech recognition: ```class VerboseApp(Application, Statistics, StreamingSpeechRecognition, ObjectDetection, FaceDetection)``` -> ```class VerboseApp(Application, Statistics, StreamingSpeechRecognition)```

Please make sure all needed dependencies are correctly installed, following the [Installation Manual](https://github.com/cltl/pepper/wiki/Installation)
